language: node_js
node_js:
- "8"
sudo: true
dist: xenial
before_install:
- export TZ=Asia/Kolkata
install:
- sudo snap install hugo
- npm install -g firebase-tools
script:
- hugo -F
deploy:
  provider: script
  skip_cleanup: true
  script: firebase deploy --token "$FIREBASE_TOKEN" -m "$TRAVIS_BUILD_NUMBER $TRAVIS_COMMIT"
