language: node_js
sudo: true
dist: trusty
before_install:
- export TZ=Asia/Kolkata
install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-64bit.deb
- sudo dpkg -i *.deb
- rm *.deb
- npm install -g firebase-tools
script:
- hugo -F --minify
deploy:
  provider: script
  skip_cleanup: true
  script: firebase deploy --token "$FIREBASE_TOKEN" -m "$TRAVIS_BUILD_NUMBER $TRAVIS_COMMIT"
