language: node_js
sudo: true
dist: trusty
install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.46/hugo_0.46_Linux-64bit.deb
- sudo dpkg -i *.deb
- rm *.deb
- npm install
- npm install -g firebase-tools
script:
- npm start
deploy:
  provider: script
  skip_cleanup: true
  script: firebase deploy --token "$FIREBASE_TOKEN" -m "$TRAVIS_BUILD_NUMBER $TRAVIS_COMMIT"

