baseurl = "https://prateekkumar.in/"
title = "Prateek Kumar"
copyright = "&copy; 2018 Prateek Kumar"

theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
paginate = 10
disqusShortname = "prateekkumar"
googleAnalytics = "UA-89128710-1"

defaultContentLanguage = "en"
hasCJKLanguage = false
defaultContentLanguageInSubdir = false

enableGitInfo = true

[outputs]
  home = ["HTML", "CSS", "RSS"]
  section = ["HTML", "RSS"]

[blackfriday]
  hrefTargetBlank = true
  fractions = true
  smartypants = true

[permalinks]
  post = "/:year/:month/:day/:filename/"
  project = "/:year/:month/:filename/"

[params]
  color_theme = "default"
  font = "default"

  # Your details.
  name = "Prateek Kumar"
  role = "Undergraduate student"
  organizations = [ { name = "IIT Hyderabad", url = "https://iith.ac.in" } ]
  gravatar = true
  email = "prateek@prateekkumar.in"
  address = "IIT Hyderabad, Kandi, Sangareddy - 502285, Telangana, INDIA"
  # office_hours = "Monday 10:00 to 13:00 or email for appointment"
  # phone = "888 888 88 88"
  # skype = "echo123"
  # telegram = ""
  keybase = "prateekkumarweb"

  map = 1
  map_api_key = "AIzaSyBMkUDs2JD9l7aXtrurTennY2rJQJO7roA"
  latitude = "17.597991"
  longitude = "78.127090"
  zoom = 15

  date_format = "Jan 2, 2006"
  time_format = "3:04 PM"

  reading_time = true
  comment_count = true
  section_pager = true

  math = false
  highlight = false
  sharing = true
  privacy_pack = true

  custom_css = ["style.css"]
  custom_js  = []

  publication_types = [
    'Uncategorized',  # 0
    'Conference paper',  # 1
    'Journal article',  # 2
    'Manuscript',  # 3
    'Report',  # 4
    'Book',  # 5
    'Book section'  # 6
  ]

  [params.talks]
    time = true

  [params.publications]
    date_format = "January, 2006"

  [params.projects]
    list_children = true

    # Publication list format.
    #   0 = Simple
    #   1 = Detailed
    #   2 = APA
    #   3 = MLA
    publication_format = 3

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:prateek@prateekkumar.in"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "https://twitter.com/prateekkumarweb"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "https://github.com/prateekkumarweb"

  [[params.social]]
    icon = "facebook"
    icon_pack = "fa"
    link = "https://www.facebook.com/prateekkumarweb"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "https://www.linkedin.com/in/prateekkumarweb/"

  [[params.social]]
    icon = "instagram"
    icon_pack = "fa"
    link = "https://www.instagram.com/prateekkumarweb/"

[params.menus]
  align_right = true

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "#publications"
  weight = 2

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 3

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 4

[[menu.main]]
  name = "Work"
  url = "#work"
  weight = 5

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 6

[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.

# Configure the English version of the website.
[Languages.en]
  languageCode = "en-in"

[Languages.hi]
  languageCode = "hi-in"
