baseurl = "https://prateekkumar.in/"
title = "Prateek Kumar"
copyright = "&copy; 2018 Prateek Kumar"

theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
paginate = 10
disqusShortname = "prateekkumar"
googleAnalytics = "UA-89128710-1"

defaultContentLanguage = "en"
hasCJKLanguage = false
defaultContentLanguageInSubdir = false

enableGitInfo = true

pygmentsCodeFences = true
pygmentsStyle = "friendly"

[outputs]
  home = ["HTML", "CSS", "RSS", "JSON"]
  section = ["HTML", "RSS"]

[blackfriday]
  hrefTargetBlank = true
  fractions = true
  smartypants = true

[permalinks]
  post = "/:year/:month/:day/:filename/"
#   project = "/:year/:month/:filename/"

[params]
  name = "Prateek Kumar"
  role = "Undergraduate student"
  id = "@prateek"
  organizations = [ { name = "IIT Hyderabad", url = "https://iith.ac.in" } ]
  gravatar = true
  email = "prateek@prateekkumar.in"
  address = "IIT Hyderabad, Kandi - 502 285, Sangareddy, Telangana, INDIA"
  keybase = "prateekkumarweb"

  map = 0
  map_api_key = ""
  latitude = "17.597991"
  longitude = "78.127090"
  zoom = 15

  color_theme = "default"
  day_night = true
  font = "default"
  description = "I am a student currently pursuing my Bachelor's degree in Computer Science and Engineering at IIT Hyderabad."
  sharing_image = ""
  twitter = "prateekkumarweb"

  date_format = "Jan 2, 2006"
  time_format = "3:04 PM MST"

  reading_time = true
  comment_count = true
  section_pager = true
  profile = true

  math = false
  highlight = false
  sharing = true
  privacy_pack = false

  custom_css = ["style.css"]
  custom_js  = []

  publication_types = [
    'Uncategorized',  # 0
    'Conference paper',  # 1
    'Journal article',  # 2
    'Manuscript',  # 3
    'Report',  # 4
    'Book',  # 5
    'Book section'  # 6
  ]

  [params.talks]
    time = true

  [params.publications]
    date_format = "January, 2006"

  [params.projects]
    list_children = true

    # Post list format.
    #   0 = Simple
    #   1 = Detailed
    #   2 = Stream
    post_format = 2

    # Publication list format.
    #   0 = Simple
    #   1 = Detailed
    #   2 = APA
    #   3 = MLA
    #   4 = Stream
    publication_format = 3

    # Talk list format.
    #   0 = Simple
    #   1 = Detailed
    #   2 = Stream
    talk_format = 2

[params.menus]
  align_right = true

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[languages.hi.menu.main]]
  name = "होम"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "#publications_selected"
  weight = 5

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 2

# [[languages.hi.menu.main]]
#   name = "पोस्ट"
#   url = "#posts"
#   weight = 2

# [[menu.main]]
#   name = "Talks"
#   url = "#talks"
#   weight = 4

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 3

[[menu.main]]
  name = "Experience"
  url = "#experience"
  weight = 6

[[languages.hi.menu.main]]
  name = "अनुभव"
  url = "#experience"
  weight = 6

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 7

[[languages.hi.menu.main]]
  name = "संपर्क"
  url = "#contact"
  weight = 7

[params.search]
  engine = 1
  [params.search.algolia]
    app_id = ""
    api_key = ""
    index_name = ""
    show_logo = false

[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

[languages.en]
  languageCode = "en-in"

[languages.hi]
  languageCode = "hi-in"
  title = "प्रतीक कुमार"
  copyright = "&copy; २०१८ प्रतीक कुमार"

  [languages.hi.params]
    name = "प्रतीक कुमार"
    role = "स्नातक छात्र"
    organizations = [ { name = "आईआईटी हैदराबाद", url = "https://iith.ac.in" } ]
    address = "आईआईटी हैदराबाद, कंदि - ५०२ २८५, संगारेड्डी, तेलंगाना, भारत"

    description = "मैं आईआईटी हैदराबाद में कंप्यूटर साइंस एंड इंजीनियरिंग में अपनी स्नातक की डिग्री पूरी कर रहा हूं।"
