[build]
    publish = "dist"
    command = "npm start"

[context.production.environment]
    HUGO_VERSION = "0.40"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"
    TZ = "Asia/Kolkata"

